version: '3.3'
services:
  
  file-ingest-db:
    container_name: file-ingest-db
    build:
        context: .
        dockerfile: Dockerfile
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices: 
      - "/dev/fuse"
    depends_on: 
      - sql-server-db
    environment: 
      ASPNETCORE_ENVIRONMENT: "Docker"

  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "hard!@1029"
      ACCEPT_EULA: "Y"