version: '3.3'
services:
  
  file-ingest-db:
    container_name: file-ingest-db
    build:
        context: .
        dockerfile: Dockerfile
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices: 
      - "/dev/fuse"
    environment: 
      ASPNETCORE_ENVIRONMENT: "Docker"