version: '3.3'
services:
  
  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "hard!@1029"
      ACCEPT_EULA: "Y"